import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"

import Header from './components/Header'
import Footer from './components/Footer'
import Nav from './components/Nav'
import {GlobalContextProvider} from './GlobalContext'
import "../assets/scss/index.scss"
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider>
            <Header />
            <Nav />
            <GlobalContextProvider>
              {children}
            </GlobalContextProvider>
            <Footer />
        </ClerkProvider>
      </body>
    </html>
  )
}
